### ISSUE TITLE
University Course Timetabling coursett-1.3.jar execution

### ISSUE THREAD

**Issue by ebracci** [UniTime/cpsolver#20]
Hi,

I was looking for run the solver without using the unitime web application using this page as example [https://www.unitime.org/cpsolver_examples.php](https://www.unitime.org/cpsolver_examples.php).

I am interested in University Course Timetabling but I have some questions.

1) Where I can find the coursett-1.3.jar? If I use the cp-solver.1.3.jar the execution returns this error:

```
Errore: impossibile inizializzare la classe principale org.cpsolver.coursett.Test
Causato da: java.lang.NoClassDefFoundError: org/apache/log4j/Layout
```

2) Is it possible to use the same jar to solve a CurriculaRequestsCourseDemands or CurriculaLastLikeCourseDemands problems? How can I do that?

Thank you for your attention.

**Comment by tomas-muller** [comment]
The individual JARs (for each problem) are available if you download the CPSolver build from the [nightly builds page](https://builds.unitime.org/#cpsolver13), e.g., [https://builds.unitime.org/cpsolver-1.3_bld238.zip](https://builds.unitime.org/cpsolver-1.3_bld238.zip). You can also use the [cpsolver-all-1.3.jar](https://builds.unitime.org/cpsolver-all-1.3.jar). In both cases, you need to have [log4j-1.2.17.jar](https://github.com/UniTime/cpsolver/raw/master/lib/log4j-1.2.17.jar) and [dom4j-2.1.3.jar](https://github.com/UniTime/cpsolver/raw/master/lib/dom4j-2.1.3.jar) in the same folder as the solver JAR.

The course timetabling problem XML already has individual student course demands listed, see [Students section of the data format](https://www.unitime.org/uct_dataformat_v24.php#students). Combining curricula with course requests or last-like course demands are done in UniTime, when the problem is loaded into the solver.
